/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "BITMAP.h"

#include "skin/skin.h"

extern GUI_CONST_STORAGE GUI_BITMAP bmcranes_n;
extern GUI_CONST_STORAGE GUI_BITMAP bmcranes_m;

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   (GUI_ID_USER + 0x00)
//#define ID_BUTTON_0   (GUI_ID_USER + 0x01)
//#define ID_BUTTON_1   (GUI_ID_USER + 0x02)
//#define ID_TEXT_0   (GUI_ID_USER + 0x03)
//#define ID_TEXT_1   (GUI_ID_USER + 0x05)
//#define ID_TEXT_2   (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 600, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};
/*static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 600, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Wind", ID_BUTTON_0, 68, 218, 140, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Distance", ID_BUTTON_1, 237, 219, 140, 120, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "建筑塔吊监控系统", ID_TEXT_0, 246, 78, 252, 37, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "text", ID_TEXT_1, 97, 341, 79, 42, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 273, 342, 72, 44, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};*/

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/

static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
/*    hItem = pMsg->hWin;
    //WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x009D7031));

    //
    // Initialization of 'Wind'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'Distance'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of '建筑塔吊监控系统'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000FFFF));
    //
    // Initialization of 'text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_32_1);
    //TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0039EEE0));
    TEXT_SetText(hItem, "20m/s");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    //TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000FFFF));
    TEXT_SetFont(hItem, GUI_FONT_32_1);
    TEXT_SetText(hItem, "50m");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;*/
    case WM_PAINT:
		GUI_DrawBitmap(&bmcranes_m, 0, 0);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
   switch(Id) {
  /* case ID_BUTTON_0: // Notifications sent by 'Wind'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Distance'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }*/
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END   
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

    static WIN_BITMAP BMP_WindowDLG1; WIN_BITMAP *pBMP_WindowDLG1;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

  	BMP_WindowDLG1.normal = &bmcranes_n;
	BMP_WindowDLG1.mark = &bmcranes_m;

	WM_SetUserData(hWin, &pBMP_WindowDLG1, sizeof(pBMP_WindowDLG1));//将指针写到用户数据区

  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
